name: Build
on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  job_1:
    name: config-template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Fetch Dependencies
      - name: Dependencies / Build config-template.conf
        run: |
          sudo apt update
          sudo apt install -y make lsb-release qemu-user-static

      # Build
      - name: Build
        run: |
          source env/setenv.sh config config-template.conf
          make

      - name: 'Tar files'
        run: tar -czvf based-config-template.tar.gz ./

      # Upload to GH Actions Artifacts
      - name: 'Upload To GH Artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: based-config-template
          path: based-config-template.tar.gz
